module.exports = {
    ACCESS: 'access',
    AUTHORIZATION: 'Authorization',
    ADMIN: 'admin',
    EMAIL: 'email',
    CONFLICTED_EMAIL: true,
    CAR: 'car',
    CAR_ID: 'car_id',
    ID: '_id',
    PASS: 'password',
    PARAMS: 'params',
    USER: 'user',
    USERS: 'users',
    USER_ID: 'user_id',
    V: '__v',
    ROLE: 'role',
    ERROR: 'error',
    REFRESH: 'refresh',
    ADMIN_NAME: 'adminname',
    MONTH: 'month',
    DAY: 'day',
    NO_REPLY: 'No reply',
    GMAIL: 'gmail',
    ID_2: 'id'
};
